// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_GetPriceReminder.proto

#ifndef PROTOBUF_Qot_5fGetPriceReminder_2eproto__INCLUDED
#define PROTOBUF_Qot_5fGetPriceReminder_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
#include "Qot_Common.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_Qot_5fGetPriceReminder_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPriceReminderItemImpl();
void InitDefaultsPriceReminderItem();
void InitDefaultsPriceReminderImpl();
void InitDefaultsPriceReminder();
void InitDefaultsC2SImpl();
void InitDefaultsC2S();
void InitDefaultsS2CImpl();
void InitDefaultsS2C();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsResponseImpl();
void InitDefaultsResponse();
inline void InitDefaults() {
  InitDefaultsPriceReminderItem();
  InitDefaultsPriceReminder();
  InitDefaultsC2S();
  InitDefaultsS2C();
  InitDefaultsRequest();
  InitDefaultsResponse();
}
}  // namespace protobuf_Qot_5fGetPriceReminder_2eproto
namespace Qot_GetPriceReminder {
class C2S;
class C2SDefaultTypeInternal;
extern C2SDefaultTypeInternal _C2S_default_instance_;
class PriceReminder;
class PriceReminderDefaultTypeInternal;
extern PriceReminderDefaultTypeInternal _PriceReminder_default_instance_;
class PriceReminderItem;
class PriceReminderItemDefaultTypeInternal;
extern PriceReminderItemDefaultTypeInternal _PriceReminderItem_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class S2C;
class S2CDefaultTypeInternal;
extern S2CDefaultTypeInternal _S2C_default_instance_;
}  // namespace Qot_GetPriceReminder
namespace Qot_GetPriceReminder {

// ===================================================================

class PriceReminderItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetPriceReminder.PriceReminderItem) */ {
 public:
  PriceReminderItem();
  virtual ~PriceReminderItem();

  PriceReminderItem(const PriceReminderItem& from);

  inline PriceReminderItem& operator=(const PriceReminderItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PriceReminderItem(PriceReminderItem&& from) noexcept
    : PriceReminderItem() {
    *this = ::std::move(from);
  }

  inline PriceReminderItem& operator=(PriceReminderItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PriceReminderItem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PriceReminderItem* internal_default_instance() {
    return reinterpret_cast<const PriceReminderItem*>(
               &_PriceReminderItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PriceReminderItem* other);
  friend void swap(PriceReminderItem& a, PriceReminderItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PriceReminderItem* New() const PROTOBUF_FINAL { return New(NULL); }

  PriceReminderItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PriceReminderItem& from);
  void MergeFrom(const PriceReminderItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PriceReminderItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string note = 4;
  bool has_note() const;
  void clear_note();
  static const int kNoteFieldNumber = 4;
  const ::std::string& note() const;
  void set_note(const ::std::string& value);
  #if LANG_CXX11
  void set_note(::std::string&& value);
  #endif
  void set_note(const char* value);
  void set_note(const char* value, size_t size);
  ::std::string* mutable_note();
  ::std::string* release_note();
  void set_allocated_note(::std::string* note);

  // required int64 key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int64 key() const;
  void set_key(::google::protobuf::int64 value);

  // required double value = 3;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 3;
  double value() const;
  void set_value(double value);

  // required int32 type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // required int32 freq = 5;
  bool has_freq() const;
  void clear_freq();
  static const int kFreqFieldNumber = 5;
  ::google::protobuf::int32 freq() const;
  void set_freq(::google::protobuf::int32 value);

  // required bool isEnable = 6;
  bool has_isenable() const;
  void clear_isenable();
  static const int kIsEnableFieldNumber = 6;
  bool isenable() const;
  void set_isenable(bool value);

  // @@protoc_insertion_point(class_scope:Qot_GetPriceReminder.PriceReminderItem)
 private:
  void set_has_key();
  void clear_has_key();
  void set_has_type();
  void clear_has_type();
  void set_has_value();
  void clear_has_value();
  void set_has_note();
  void clear_has_note();
  void set_has_freq();
  void clear_has_freq();
  void set_has_isenable();
  void clear_has_isenable();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr note_;
  ::google::protobuf::int64 key_;
  double value_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 freq_;
  bool isenable_;
  friend struct ::protobuf_Qot_5fGetPriceReminder_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetPriceReminder_2eproto::InitDefaultsPriceReminderItemImpl();
};
// -------------------------------------------------------------------

class PriceReminder : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetPriceReminder.PriceReminder) */ {
 public:
  PriceReminder();
  virtual ~PriceReminder();

  PriceReminder(const PriceReminder& from);

  inline PriceReminder& operator=(const PriceReminder& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PriceReminder(PriceReminder&& from) noexcept
    : PriceReminder() {
    *this = ::std::move(from);
  }

  inline PriceReminder& operator=(PriceReminder&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PriceReminder& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PriceReminder* internal_default_instance() {
    return reinterpret_cast<const PriceReminder*>(
               &_PriceReminder_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PriceReminder* other);
  friend void swap(PriceReminder& a, PriceReminder& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PriceReminder* New() const PROTOBUF_FINAL { return New(NULL); }

  PriceReminder* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PriceReminder& from);
  void MergeFrom(const PriceReminder& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PriceReminder* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Qot_GetPriceReminder.PriceReminderItem itemList = 2;
  int itemlist_size() const;
  void clear_itemlist();
  static const int kItemListFieldNumber = 2;
  const ::Qot_GetPriceReminder::PriceReminderItem& itemlist(int index) const;
  ::Qot_GetPriceReminder::PriceReminderItem* mutable_itemlist(int index);
  ::Qot_GetPriceReminder::PriceReminderItem* add_itemlist();
  ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminderItem >*
      mutable_itemlist();
  const ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminderItem >&
      itemlist() const;

  // required .Qot_Common.Security security = 1;
  bool has_security() const;
  void clear_security();
  static const int kSecurityFieldNumber = 1;
  const ::Qot_Common::Security& security() const;
  ::Qot_Common::Security* release_security();
  ::Qot_Common::Security* mutable_security();
  void set_allocated_security(::Qot_Common::Security* security);

  // @@protoc_insertion_point(class_scope:Qot_GetPriceReminder.PriceReminder)
 private:
  void set_has_security();
  void clear_has_security();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminderItem > itemlist_;
  ::Qot_Common::Security* security_;
  friend struct ::protobuf_Qot_5fGetPriceReminder_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetPriceReminder_2eproto::InitDefaultsPriceReminderImpl();
};
// -------------------------------------------------------------------

class C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetPriceReminder.C2S) */ {
 public:
  C2S();
  virtual ~C2S();

  C2S(const C2S& from);

  inline C2S& operator=(const C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  C2S(C2S&& from) noexcept
    : C2S() {
    *this = ::std::move(from);
  }

  inline C2S& operator=(C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const C2S* internal_default_instance() {
    return reinterpret_cast<const C2S*>(
               &_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(C2S* other);
  friend void swap(C2S& a, C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S& from);
  void MergeFrom(const C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Qot_Common.Security security = 1;
  bool has_security() const;
  void clear_security();
  static const int kSecurityFieldNumber = 1;
  const ::Qot_Common::Security& security() const;
  ::Qot_Common::Security* release_security();
  ::Qot_Common::Security* mutable_security();
  void set_allocated_security(::Qot_Common::Security* security);

  // optional int32 market = 2;
  bool has_market() const;
  void clear_market();
  static const int kMarketFieldNumber = 2;
  ::google::protobuf::int32 market() const;
  void set_market(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Qot_GetPriceReminder.C2S)
 private:
  void set_has_security();
  void clear_has_security();
  void set_has_market();
  void clear_has_market();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Qot_Common::Security* security_;
  ::google::protobuf::int32 market_;
  friend struct ::protobuf_Qot_5fGetPriceReminder_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetPriceReminder_2eproto::InitDefaultsC2SImpl();
};
// -------------------------------------------------------------------

class S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetPriceReminder.S2C) */ {
 public:
  S2C();
  virtual ~S2C();

  S2C(const S2C& from);

  inline S2C& operator=(const S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  S2C(S2C&& from) noexcept
    : S2C() {
    *this = ::std::move(from);
  }

  inline S2C& operator=(S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const S2C* internal_default_instance() {
    return reinterpret_cast<const S2C*>(
               &_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(S2C* other);
  friend void swap(S2C& a, S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C& from);
  void MergeFrom(const S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Qot_GetPriceReminder.PriceReminder priceReminderList = 1;
  int pricereminderlist_size() const;
  void clear_pricereminderlist();
  static const int kPriceReminderListFieldNumber = 1;
  const ::Qot_GetPriceReminder::PriceReminder& pricereminderlist(int index) const;
  ::Qot_GetPriceReminder::PriceReminder* mutable_pricereminderlist(int index);
  ::Qot_GetPriceReminder::PriceReminder* add_pricereminderlist();
  ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminder >*
      mutable_pricereminderlist();
  const ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminder >&
      pricereminderlist() const;

  // @@protoc_insertion_point(class_scope:Qot_GetPriceReminder.S2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminder > pricereminderlist_;
  friend struct ::protobuf_Qot_5fGetPriceReminder_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetPriceReminder_2eproto::InitDefaultsS2CImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetPriceReminder.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Qot_GetPriceReminder.C2S c2s = 1;
  bool has_c2s() const;
  void clear_c2s();
  static const int kC2SFieldNumber = 1;
  const ::Qot_GetPriceReminder::C2S& c2s() const;
  ::Qot_GetPriceReminder::C2S* release_c2s();
  ::Qot_GetPriceReminder::C2S* mutable_c2s();
  void set_allocated_c2s(::Qot_GetPriceReminder::C2S* c2s);

  // @@protoc_insertion_point(class_scope:Qot_GetPriceReminder.Request)
 private:
  void set_has_c2s();
  void clear_has_c2s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Qot_GetPriceReminder::C2S* c2s_;
  friend struct ::protobuf_Qot_5fGetPriceReminder_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetPriceReminder_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetPriceReminder.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const PROTOBUF_FINAL { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string retMsg = 2;
  bool has_retmsg() const;
  void clear_retmsg();
  static const int kRetMsgFieldNumber = 2;
  const ::std::string& retmsg() const;
  void set_retmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_retmsg(::std::string&& value);
  #endif
  void set_retmsg(const char* value);
  void set_retmsg(const char* value, size_t size);
  ::std::string* mutable_retmsg();
  ::std::string* release_retmsg();
  void set_allocated_retmsg(::std::string* retmsg);

  // optional .Qot_GetPriceReminder.S2C s2c = 4;
  bool has_s2c() const;
  void clear_s2c();
  static const int kS2CFieldNumber = 4;
  const ::Qot_GetPriceReminder::S2C& s2c() const;
  ::Qot_GetPriceReminder::S2C* release_s2c();
  ::Qot_GetPriceReminder::S2C* mutable_s2c();
  void set_allocated_s2c(::Qot_GetPriceReminder::S2C* s2c);

  // optional int32 errCode = 3;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 3;
  ::google::protobuf::int32 errcode() const;
  void set_errcode(::google::protobuf::int32 value);

  // required int32 retType = 1 [default = -400];
  bool has_rettype() const;
  void clear_rettype();
  static const int kRetTypeFieldNumber = 1;
  ::google::protobuf::int32 rettype() const;
  void set_rettype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Qot_GetPriceReminder.Response)
 private:
  void set_has_rettype();
  void clear_has_rettype();
  void set_has_retmsg();
  void clear_has_retmsg();
  void set_has_errcode();
  void clear_has_errcode();
  void set_has_s2c();
  void clear_has_s2c();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr retmsg_;
  ::Qot_GetPriceReminder::S2C* s2c_;
  ::google::protobuf::int32 errcode_;
  ::google::protobuf::int32 rettype_;
  friend struct ::protobuf_Qot_5fGetPriceReminder_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetPriceReminder_2eproto::InitDefaultsResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PriceReminderItem

// required int64 key = 1;
inline bool PriceReminderItem::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PriceReminderItem::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PriceReminderItem::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PriceReminderItem::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
  clear_has_key();
}
inline ::google::protobuf::int64 PriceReminderItem::key() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminderItem.key)
  return key_;
}
inline void PriceReminderItem::set_key(::google::protobuf::int64 value) {
  set_has_key();
  key_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.PriceReminderItem.key)
}

// required int32 type = 2;
inline bool PriceReminderItem::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PriceReminderItem::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PriceReminderItem::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PriceReminderItem::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 PriceReminderItem::type() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminderItem.type)
  return type_;
}
inline void PriceReminderItem::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.PriceReminderItem.type)
}

// required double value = 3;
inline bool PriceReminderItem::has_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PriceReminderItem::set_has_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PriceReminderItem::clear_has_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PriceReminderItem::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline double PriceReminderItem::value() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminderItem.value)
  return value_;
}
inline void PriceReminderItem::set_value(double value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.PriceReminderItem.value)
}

// required string note = 4;
inline bool PriceReminderItem::has_note() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PriceReminderItem::set_has_note() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PriceReminderItem::clear_has_note() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PriceReminderItem::clear_note() {
  note_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_note();
}
inline const ::std::string& PriceReminderItem::note() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminderItem.note)
  return note_.GetNoArena();
}
inline void PriceReminderItem::set_note(const ::std::string& value) {
  set_has_note();
  note_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.PriceReminderItem.note)
}
#if LANG_CXX11
inline void PriceReminderItem::set_note(::std::string&& value) {
  set_has_note();
  note_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_GetPriceReminder.PriceReminderItem.note)
}
#endif
inline void PriceReminderItem::set_note(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_note();
  note_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_GetPriceReminder.PriceReminderItem.note)
}
inline void PriceReminderItem::set_note(const char* value, size_t size) {
  set_has_note();
  note_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_GetPriceReminder.PriceReminderItem.note)
}
inline ::std::string* PriceReminderItem::mutable_note() {
  set_has_note();
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.PriceReminderItem.note)
  return note_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PriceReminderItem::release_note() {
  // @@protoc_insertion_point(field_release:Qot_GetPriceReminder.PriceReminderItem.note)
  clear_has_note();
  return note_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PriceReminderItem::set_allocated_note(::std::string* note) {
  if (note != NULL) {
    set_has_note();
  } else {
    clear_has_note();
  }
  note_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), note);
  // @@protoc_insertion_point(field_set_allocated:Qot_GetPriceReminder.PriceReminderItem.note)
}

// required int32 freq = 5;
inline bool PriceReminderItem::has_freq() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PriceReminderItem::set_has_freq() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PriceReminderItem::clear_has_freq() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PriceReminderItem::clear_freq() {
  freq_ = 0;
  clear_has_freq();
}
inline ::google::protobuf::int32 PriceReminderItem::freq() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminderItem.freq)
  return freq_;
}
inline void PriceReminderItem::set_freq(::google::protobuf::int32 value) {
  set_has_freq();
  freq_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.PriceReminderItem.freq)
}

// required bool isEnable = 6;
inline bool PriceReminderItem::has_isenable() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PriceReminderItem::set_has_isenable() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PriceReminderItem::clear_has_isenable() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PriceReminderItem::clear_isenable() {
  isenable_ = false;
  clear_has_isenable();
}
inline bool PriceReminderItem::isenable() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminderItem.isEnable)
  return isenable_;
}
inline void PriceReminderItem::set_isenable(bool value) {
  set_has_isenable();
  isenable_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.PriceReminderItem.isEnable)
}

// -------------------------------------------------------------------

// PriceReminder

// required .Qot_Common.Security security = 1;
inline bool PriceReminder::has_security() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PriceReminder::set_has_security() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PriceReminder::clear_has_security() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Qot_Common::Security& PriceReminder::security() const {
  const ::Qot_Common::Security* p = security_;
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminder.security)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::Security*>(
      &::Qot_Common::_Security_default_instance_);
}
inline ::Qot_Common::Security* PriceReminder::release_security() {
  // @@protoc_insertion_point(field_release:Qot_GetPriceReminder.PriceReminder.security)
  clear_has_security();
  ::Qot_Common::Security* temp = security_;
  security_ = NULL;
  return temp;
}
inline ::Qot_Common::Security* PriceReminder::mutable_security() {
  set_has_security();
  if (security_ == NULL) {
    security_ = new ::Qot_Common::Security;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.PriceReminder.security)
  return security_;
}
inline void PriceReminder::set_allocated_security(::Qot_Common::Security* security) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(security_);
  }
  if (security) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      security = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, security, submessage_arena);
    }
    set_has_security();
  } else {
    clear_has_security();
  }
  security_ = security;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetPriceReminder.PriceReminder.security)
}

// repeated .Qot_GetPriceReminder.PriceReminderItem itemList = 2;
inline int PriceReminder::itemlist_size() const {
  return itemlist_.size();
}
inline void PriceReminder::clear_itemlist() {
  itemlist_.Clear();
}
inline const ::Qot_GetPriceReminder::PriceReminderItem& PriceReminder::itemlist(int index) const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.PriceReminder.itemList)
  return itemlist_.Get(index);
}
inline ::Qot_GetPriceReminder::PriceReminderItem* PriceReminder::mutable_itemlist(int index) {
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.PriceReminder.itemList)
  return itemlist_.Mutable(index);
}
inline ::Qot_GetPriceReminder::PriceReminderItem* PriceReminder::add_itemlist() {
  // @@protoc_insertion_point(field_add:Qot_GetPriceReminder.PriceReminder.itemList)
  return itemlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminderItem >*
PriceReminder::mutable_itemlist() {
  // @@protoc_insertion_point(field_mutable_list:Qot_GetPriceReminder.PriceReminder.itemList)
  return &itemlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminderItem >&
PriceReminder::itemlist() const {
  // @@protoc_insertion_point(field_list:Qot_GetPriceReminder.PriceReminder.itemList)
  return itemlist_;
}

// -------------------------------------------------------------------

// C2S

// optional .Qot_Common.Security security = 1;
inline bool C2S::has_security() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S::set_has_security() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S::clear_has_security() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Qot_Common::Security& C2S::security() const {
  const ::Qot_Common::Security* p = security_;
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.C2S.security)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::Security*>(
      &::Qot_Common::_Security_default_instance_);
}
inline ::Qot_Common::Security* C2S::release_security() {
  // @@protoc_insertion_point(field_release:Qot_GetPriceReminder.C2S.security)
  clear_has_security();
  ::Qot_Common::Security* temp = security_;
  security_ = NULL;
  return temp;
}
inline ::Qot_Common::Security* C2S::mutable_security() {
  set_has_security();
  if (security_ == NULL) {
    security_ = new ::Qot_Common::Security;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.C2S.security)
  return security_;
}
inline void C2S::set_allocated_security(::Qot_Common::Security* security) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(security_);
  }
  if (security) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      security = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, security, submessage_arena);
    }
    set_has_security();
  } else {
    clear_has_security();
  }
  security_ = security;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetPriceReminder.C2S.security)
}

// optional int32 market = 2;
inline bool C2S::has_market() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2S::set_has_market() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2S::clear_has_market() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2S::clear_market() {
  market_ = 0;
  clear_has_market();
}
inline ::google::protobuf::int32 C2S::market() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.C2S.market)
  return market_;
}
inline void C2S::set_market(::google::protobuf::int32 value) {
  set_has_market();
  market_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.C2S.market)
}

// -------------------------------------------------------------------

// S2C

// repeated .Qot_GetPriceReminder.PriceReminder priceReminderList = 1;
inline int S2C::pricereminderlist_size() const {
  return pricereminderlist_.size();
}
inline void S2C::clear_pricereminderlist() {
  pricereminderlist_.Clear();
}
inline const ::Qot_GetPriceReminder::PriceReminder& S2C::pricereminderlist(int index) const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.S2C.priceReminderList)
  return pricereminderlist_.Get(index);
}
inline ::Qot_GetPriceReminder::PriceReminder* S2C::mutable_pricereminderlist(int index) {
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.S2C.priceReminderList)
  return pricereminderlist_.Mutable(index);
}
inline ::Qot_GetPriceReminder::PriceReminder* S2C::add_pricereminderlist() {
  // @@protoc_insertion_point(field_add:Qot_GetPriceReminder.S2C.priceReminderList)
  return pricereminderlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminder >*
S2C::mutable_pricereminderlist() {
  // @@protoc_insertion_point(field_mutable_list:Qot_GetPriceReminder.S2C.priceReminderList)
  return &pricereminderlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Qot_GetPriceReminder::PriceReminder >&
S2C::pricereminderlist() const {
  // @@protoc_insertion_point(field_list:Qot_GetPriceReminder.S2C.priceReminderList)
  return pricereminderlist_;
}

// -------------------------------------------------------------------

// Request

// required .Qot_GetPriceReminder.C2S c2s = 1;
inline bool Request::has_c2s() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_c2s() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_c2s() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_c2s() {
  if (c2s_ != NULL) c2s_->Clear();
  clear_has_c2s();
}
inline const ::Qot_GetPriceReminder::C2S& Request::c2s() const {
  const ::Qot_GetPriceReminder::C2S* p = c2s_;
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.Request.c2s)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_GetPriceReminder::C2S*>(
      &::Qot_GetPriceReminder::_C2S_default_instance_);
}
inline ::Qot_GetPriceReminder::C2S* Request::release_c2s() {
  // @@protoc_insertion_point(field_release:Qot_GetPriceReminder.Request.c2s)
  clear_has_c2s();
  ::Qot_GetPriceReminder::C2S* temp = c2s_;
  c2s_ = NULL;
  return temp;
}
inline ::Qot_GetPriceReminder::C2S* Request::mutable_c2s() {
  set_has_c2s();
  if (c2s_ == NULL) {
    c2s_ = new ::Qot_GetPriceReminder::C2S;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.Request.c2s)
  return c2s_;
}
inline void Request::set_allocated_c2s(::Qot_GetPriceReminder::C2S* c2s) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete c2s_;
  }
  if (c2s) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      c2s = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, c2s, submessage_arena);
    }
    set_has_c2s();
  } else {
    clear_has_c2s();
  }
  c2s_ = c2s;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetPriceReminder.Request.c2s)
}

// -------------------------------------------------------------------

// Response

// required int32 retType = 1 [default = -400];
inline bool Response::has_rettype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_rettype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_rettype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_rettype() {
  rettype_ = -400;
  clear_has_rettype();
}
inline ::google::protobuf::int32 Response::rettype() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.Response.retType)
  return rettype_;
}
inline void Response::set_rettype(::google::protobuf::int32 value) {
  set_has_rettype();
  rettype_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.Response.retType)
}

// optional string retMsg = 2;
inline bool Response::has_retmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_retmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_retmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_retmsg() {
  retmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_retmsg();
}
inline const ::std::string& Response::retmsg() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.Response.retMsg)
  return retmsg_.GetNoArena();
}
inline void Response::set_retmsg(const ::std::string& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.Response.retMsg)
}
#if LANG_CXX11
inline void Response::set_retmsg(::std::string&& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_GetPriceReminder.Response.retMsg)
}
#endif
inline void Response::set_retmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_GetPriceReminder.Response.retMsg)
}
inline void Response::set_retmsg(const char* value, size_t size) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_GetPriceReminder.Response.retMsg)
}
inline ::std::string* Response::mutable_retmsg() {
  set_has_retmsg();
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.Response.retMsg)
  return retmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_retmsg() {
  // @@protoc_insertion_point(field_release:Qot_GetPriceReminder.Response.retMsg)
  clear_has_retmsg();
  return retmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_retmsg(::std::string* retmsg) {
  if (retmsg != NULL) {
    set_has_retmsg();
  } else {
    clear_has_retmsg();
  }
  retmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), retmsg);
  // @@protoc_insertion_point(field_set_allocated:Qot_GetPriceReminder.Response.retMsg)
}

// optional int32 errCode = 3;
inline bool Response::has_errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_errcode() {
  errcode_ = 0;
  clear_has_errcode();
}
inline ::google::protobuf::int32 Response::errcode() const {
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.Response.errCode)
  return errcode_;
}
inline void Response::set_errcode(::google::protobuf::int32 value) {
  set_has_errcode();
  errcode_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetPriceReminder.Response.errCode)
}

// optional .Qot_GetPriceReminder.S2C s2c = 4;
inline bool Response::has_s2c() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_s2c() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_s2c() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_s2c() {
  if (s2c_ != NULL) s2c_->Clear();
  clear_has_s2c();
}
inline const ::Qot_GetPriceReminder::S2C& Response::s2c() const {
  const ::Qot_GetPriceReminder::S2C* p = s2c_;
  // @@protoc_insertion_point(field_get:Qot_GetPriceReminder.Response.s2c)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_GetPriceReminder::S2C*>(
      &::Qot_GetPriceReminder::_S2C_default_instance_);
}
inline ::Qot_GetPriceReminder::S2C* Response::release_s2c() {
  // @@protoc_insertion_point(field_release:Qot_GetPriceReminder.Response.s2c)
  clear_has_s2c();
  ::Qot_GetPriceReminder::S2C* temp = s2c_;
  s2c_ = NULL;
  return temp;
}
inline ::Qot_GetPriceReminder::S2C* Response::mutable_s2c() {
  set_has_s2c();
  if (s2c_ == NULL) {
    s2c_ = new ::Qot_GetPriceReminder::S2C;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetPriceReminder.Response.s2c)
  return s2c_;
}
inline void Response::set_allocated_s2c(::Qot_GetPriceReminder::S2C* s2c) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete s2c_;
  }
  if (s2c) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      s2c = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, s2c, submessage_arena);
    }
    set_has_s2c();
  } else {
    clear_has_s2c();
  }
  s2c_ = s2c;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetPriceReminder.Response.s2c)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Qot_GetPriceReminder

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Qot_5fGetPriceReminder_2eproto__INCLUDED
