// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trd_GetMarginRatio.proto

#ifndef PROTOBUF_Trd_5fGetMarginRatio_2eproto__INCLUDED
#define PROTOBUF_Trd_5fGetMarginRatio_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Trd_Common.pb.h"
#include "Qot_Common.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_Trd_5fGetMarginRatio_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsMarginRatioInfoImpl();
void InitDefaultsMarginRatioInfo();
void InitDefaultsC2SImpl();
void InitDefaultsC2S();
void InitDefaultsS2CImpl();
void InitDefaultsS2C();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsResponseImpl();
void InitDefaultsResponse();
inline void InitDefaults() {
  InitDefaultsMarginRatioInfo();
  InitDefaultsC2S();
  InitDefaultsS2C();
  InitDefaultsRequest();
  InitDefaultsResponse();
}
}  // namespace protobuf_Trd_5fGetMarginRatio_2eproto
namespace Trd_GetMarginRatio {
class C2S;
class C2SDefaultTypeInternal;
extern C2SDefaultTypeInternal _C2S_default_instance_;
class MarginRatioInfo;
class MarginRatioInfoDefaultTypeInternal;
extern MarginRatioInfoDefaultTypeInternal _MarginRatioInfo_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class S2C;
class S2CDefaultTypeInternal;
extern S2CDefaultTypeInternal _S2C_default_instance_;
}  // namespace Trd_GetMarginRatio
namespace Trd_GetMarginRatio {

// ===================================================================

class MarginRatioInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_GetMarginRatio.MarginRatioInfo) */ {
 public:
  MarginRatioInfo();
  virtual ~MarginRatioInfo();

  MarginRatioInfo(const MarginRatioInfo& from);

  inline MarginRatioInfo& operator=(const MarginRatioInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MarginRatioInfo(MarginRatioInfo&& from) noexcept
    : MarginRatioInfo() {
    *this = ::std::move(from);
  }

  inline MarginRatioInfo& operator=(MarginRatioInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MarginRatioInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MarginRatioInfo* internal_default_instance() {
    return reinterpret_cast<const MarginRatioInfo*>(
               &_MarginRatioInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MarginRatioInfo* other);
  friend void swap(MarginRatioInfo& a, MarginRatioInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MarginRatioInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  MarginRatioInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MarginRatioInfo& from);
  void MergeFrom(const MarginRatioInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MarginRatioInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Qot_Common.Security security = 1;
  bool has_security() const;
  void clear_security();
  static const int kSecurityFieldNumber = 1;
  const ::Qot_Common::Security& security() const;
  ::Qot_Common::Security* release_security();
  ::Qot_Common::Security* mutable_security();
  void set_allocated_security(::Qot_Common::Security* security);

  // optional double shortPoolRemain = 4;
  bool has_shortpoolremain() const;
  void clear_shortpoolremain();
  static const int kShortPoolRemainFieldNumber = 4;
  double shortpoolremain() const;
  void set_shortpoolremain(double value);

  // optional double shortFeeRate = 5;
  bool has_shortfeerate() const;
  void clear_shortfeerate();
  static const int kShortFeeRateFieldNumber = 5;
  double shortfeerate() const;
  void set_shortfeerate(double value);

  // optional double alertLongRatio = 6;
  bool has_alertlongratio() const;
  void clear_alertlongratio();
  static const int kAlertLongRatioFieldNumber = 6;
  double alertlongratio() const;
  void set_alertlongratio(double value);

  // optional double alertShortRatio = 7;
  bool has_alertshortratio() const;
  void clear_alertshortratio();
  static const int kAlertShortRatioFieldNumber = 7;
  double alertshortratio() const;
  void set_alertshortratio(double value);

  // optional double imLongRatio = 8;
  bool has_imlongratio() const;
  void clear_imlongratio();
  static const int kImLongRatioFieldNumber = 8;
  double imlongratio() const;
  void set_imlongratio(double value);

  // optional double imShortRatio = 9;
  bool has_imshortratio() const;
  void clear_imshortratio();
  static const int kImShortRatioFieldNumber = 9;
  double imshortratio() const;
  void set_imshortratio(double value);

  // optional double mcmLongRatio = 10;
  bool has_mcmlongratio() const;
  void clear_mcmlongratio();
  static const int kMcmLongRatioFieldNumber = 10;
  double mcmlongratio() const;
  void set_mcmlongratio(double value);

  // optional double mcmShortRatio = 11;
  bool has_mcmshortratio() const;
  void clear_mcmshortratio();
  static const int kMcmShortRatioFieldNumber = 11;
  double mcmshortratio() const;
  void set_mcmshortratio(double value);

  // optional double mmLongRatio = 12;
  bool has_mmlongratio() const;
  void clear_mmlongratio();
  static const int kMmLongRatioFieldNumber = 12;
  double mmlongratio() const;
  void set_mmlongratio(double value);

  // optional double mmShortRatio = 13;
  bool has_mmshortratio() const;
  void clear_mmshortratio();
  static const int kMmShortRatioFieldNumber = 13;
  double mmshortratio() const;
  void set_mmshortratio(double value);

  // optional bool isLongPermit = 2;
  bool has_islongpermit() const;
  void clear_islongpermit();
  static const int kIsLongPermitFieldNumber = 2;
  bool islongpermit() const;
  void set_islongpermit(bool value);

  // optional bool isShortPermit = 3;
  bool has_isshortpermit() const;
  void clear_isshortpermit();
  static const int kIsShortPermitFieldNumber = 3;
  bool isshortpermit() const;
  void set_isshortpermit(bool value);

  // @@protoc_insertion_point(class_scope:Trd_GetMarginRatio.MarginRatioInfo)
 private:
  void set_has_security();
  void clear_has_security();
  void set_has_islongpermit();
  void clear_has_islongpermit();
  void set_has_isshortpermit();
  void clear_has_isshortpermit();
  void set_has_shortpoolremain();
  void clear_has_shortpoolremain();
  void set_has_shortfeerate();
  void clear_has_shortfeerate();
  void set_has_alertlongratio();
  void clear_has_alertlongratio();
  void set_has_alertshortratio();
  void clear_has_alertshortratio();
  void set_has_imlongratio();
  void clear_has_imlongratio();
  void set_has_imshortratio();
  void clear_has_imshortratio();
  void set_has_mcmlongratio();
  void clear_has_mcmlongratio();
  void set_has_mcmshortratio();
  void clear_has_mcmshortratio();
  void set_has_mmlongratio();
  void clear_has_mmlongratio();
  void set_has_mmshortratio();
  void clear_has_mmshortratio();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Qot_Common::Security* security_;
  double shortpoolremain_;
  double shortfeerate_;
  double alertlongratio_;
  double alertshortratio_;
  double imlongratio_;
  double imshortratio_;
  double mcmlongratio_;
  double mcmshortratio_;
  double mmlongratio_;
  double mmshortratio_;
  bool islongpermit_;
  bool isshortpermit_;
  friend struct ::protobuf_Trd_5fGetMarginRatio_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fGetMarginRatio_2eproto::InitDefaultsMarginRatioInfoImpl();
};
// -------------------------------------------------------------------

class C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_GetMarginRatio.C2S) */ {
 public:
  C2S();
  virtual ~C2S();

  C2S(const C2S& from);

  inline C2S& operator=(const C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  C2S(C2S&& from) noexcept
    : C2S() {
    *this = ::std::move(from);
  }

  inline C2S& operator=(C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const C2S* internal_default_instance() {
    return reinterpret_cast<const C2S*>(
               &_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(C2S* other);
  friend void swap(C2S& a, C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S& from);
  void MergeFrom(const C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Qot_Common.Security securityList = 2;
  int securitylist_size() const;
  void clear_securitylist();
  static const int kSecurityListFieldNumber = 2;
  const ::Qot_Common::Security& securitylist(int index) const;
  ::Qot_Common::Security* mutable_securitylist(int index);
  ::Qot_Common::Security* add_securitylist();
  ::google::protobuf::RepeatedPtrField< ::Qot_Common::Security >*
      mutable_securitylist();
  const ::google::protobuf::RepeatedPtrField< ::Qot_Common::Security >&
      securitylist() const;

  // required .Trd_Common.TrdHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::Trd_Common::TrdHeader& header() const;
  ::Trd_Common::TrdHeader* release_header();
  ::Trd_Common::TrdHeader* mutable_header();
  void set_allocated_header(::Trd_Common::TrdHeader* header);

  // @@protoc_insertion_point(class_scope:Trd_GetMarginRatio.C2S)
 private:
  void set_has_header();
  void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Qot_Common::Security > securitylist_;
  ::Trd_Common::TrdHeader* header_;
  friend struct ::protobuf_Trd_5fGetMarginRatio_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fGetMarginRatio_2eproto::InitDefaultsC2SImpl();
};
// -------------------------------------------------------------------

class S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_GetMarginRatio.S2C) */ {
 public:
  S2C();
  virtual ~S2C();

  S2C(const S2C& from);

  inline S2C& operator=(const S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  S2C(S2C&& from) noexcept
    : S2C() {
    *this = ::std::move(from);
  }

  inline S2C& operator=(S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const S2C* internal_default_instance() {
    return reinterpret_cast<const S2C*>(
               &_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(S2C* other);
  friend void swap(S2C& a, S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C& from);
  void MergeFrom(const S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Trd_GetMarginRatio.MarginRatioInfo marginRatioInfoList = 2;
  int marginratioinfolist_size() const;
  void clear_marginratioinfolist();
  static const int kMarginRatioInfoListFieldNumber = 2;
  const ::Trd_GetMarginRatio::MarginRatioInfo& marginratioinfolist(int index) const;
  ::Trd_GetMarginRatio::MarginRatioInfo* mutable_marginratioinfolist(int index);
  ::Trd_GetMarginRatio::MarginRatioInfo* add_marginratioinfolist();
  ::google::protobuf::RepeatedPtrField< ::Trd_GetMarginRatio::MarginRatioInfo >*
      mutable_marginratioinfolist();
  const ::google::protobuf::RepeatedPtrField< ::Trd_GetMarginRatio::MarginRatioInfo >&
      marginratioinfolist() const;

  // required .Trd_Common.TrdHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::Trd_Common::TrdHeader& header() const;
  ::Trd_Common::TrdHeader* release_header();
  ::Trd_Common::TrdHeader* mutable_header();
  void set_allocated_header(::Trd_Common::TrdHeader* header);

  // @@protoc_insertion_point(class_scope:Trd_GetMarginRatio.S2C)
 private:
  void set_has_header();
  void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Trd_GetMarginRatio::MarginRatioInfo > marginratioinfolist_;
  ::Trd_Common::TrdHeader* header_;
  friend struct ::protobuf_Trd_5fGetMarginRatio_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fGetMarginRatio_2eproto::InitDefaultsS2CImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_GetMarginRatio.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Trd_GetMarginRatio.C2S c2s = 1;
  bool has_c2s() const;
  void clear_c2s();
  static const int kC2SFieldNumber = 1;
  const ::Trd_GetMarginRatio::C2S& c2s() const;
  ::Trd_GetMarginRatio::C2S* release_c2s();
  ::Trd_GetMarginRatio::C2S* mutable_c2s();
  void set_allocated_c2s(::Trd_GetMarginRatio::C2S* c2s);

  // @@protoc_insertion_point(class_scope:Trd_GetMarginRatio.Request)
 private:
  void set_has_c2s();
  void clear_has_c2s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Trd_GetMarginRatio::C2S* c2s_;
  friend struct ::protobuf_Trd_5fGetMarginRatio_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fGetMarginRatio_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_GetMarginRatio.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const PROTOBUF_FINAL { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string retMsg = 2;
  bool has_retmsg() const;
  void clear_retmsg();
  static const int kRetMsgFieldNumber = 2;
  const ::std::string& retmsg() const;
  void set_retmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_retmsg(::std::string&& value);
  #endif
  void set_retmsg(const char* value);
  void set_retmsg(const char* value, size_t size);
  ::std::string* mutable_retmsg();
  ::std::string* release_retmsg();
  void set_allocated_retmsg(::std::string* retmsg);

  // optional .Trd_GetMarginRatio.S2C s2c = 4;
  bool has_s2c() const;
  void clear_s2c();
  static const int kS2CFieldNumber = 4;
  const ::Trd_GetMarginRatio::S2C& s2c() const;
  ::Trd_GetMarginRatio::S2C* release_s2c();
  ::Trd_GetMarginRatio::S2C* mutable_s2c();
  void set_allocated_s2c(::Trd_GetMarginRatio::S2C* s2c);

  // optional int32 errCode = 3;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 3;
  ::google::protobuf::int32 errcode() const;
  void set_errcode(::google::protobuf::int32 value);

  // required int32 retType = 1 [default = -400];
  bool has_rettype() const;
  void clear_rettype();
  static const int kRetTypeFieldNumber = 1;
  ::google::protobuf::int32 rettype() const;
  void set_rettype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Trd_GetMarginRatio.Response)
 private:
  void set_has_rettype();
  void clear_has_rettype();
  void set_has_retmsg();
  void clear_has_retmsg();
  void set_has_errcode();
  void clear_has_errcode();
  void set_has_s2c();
  void clear_has_s2c();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr retmsg_;
  ::Trd_GetMarginRatio::S2C* s2c_;
  ::google::protobuf::int32 errcode_;
  ::google::protobuf::int32 rettype_;
  friend struct ::protobuf_Trd_5fGetMarginRatio_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fGetMarginRatio_2eproto::InitDefaultsResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MarginRatioInfo

// required .Qot_Common.Security security = 1;
inline bool MarginRatioInfo::has_security() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MarginRatioInfo::set_has_security() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MarginRatioInfo::clear_has_security() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Qot_Common::Security& MarginRatioInfo::security() const {
  const ::Qot_Common::Security* p = security_;
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.security)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::Security*>(
      &::Qot_Common::_Security_default_instance_);
}
inline ::Qot_Common::Security* MarginRatioInfo::release_security() {
  // @@protoc_insertion_point(field_release:Trd_GetMarginRatio.MarginRatioInfo.security)
  clear_has_security();
  ::Qot_Common::Security* temp = security_;
  security_ = NULL;
  return temp;
}
inline ::Qot_Common::Security* MarginRatioInfo::mutable_security() {
  set_has_security();
  if (security_ == NULL) {
    security_ = new ::Qot_Common::Security;
  }
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.MarginRatioInfo.security)
  return security_;
}
inline void MarginRatioInfo::set_allocated_security(::Qot_Common::Security* security) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(security_);
  }
  if (security) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      security = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, security, submessage_arena);
    }
    set_has_security();
  } else {
    clear_has_security();
  }
  security_ = security;
  // @@protoc_insertion_point(field_set_allocated:Trd_GetMarginRatio.MarginRatioInfo.security)
}

// optional bool isLongPermit = 2;
inline bool MarginRatioInfo::has_islongpermit() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void MarginRatioInfo::set_has_islongpermit() {
  _has_bits_[0] |= 0x00000800u;
}
inline void MarginRatioInfo::clear_has_islongpermit() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void MarginRatioInfo::clear_islongpermit() {
  islongpermit_ = false;
  clear_has_islongpermit();
}
inline bool MarginRatioInfo::islongpermit() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.isLongPermit)
  return islongpermit_;
}
inline void MarginRatioInfo::set_islongpermit(bool value) {
  set_has_islongpermit();
  islongpermit_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.isLongPermit)
}

// optional bool isShortPermit = 3;
inline bool MarginRatioInfo::has_isshortpermit() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void MarginRatioInfo::set_has_isshortpermit() {
  _has_bits_[0] |= 0x00001000u;
}
inline void MarginRatioInfo::clear_has_isshortpermit() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void MarginRatioInfo::clear_isshortpermit() {
  isshortpermit_ = false;
  clear_has_isshortpermit();
}
inline bool MarginRatioInfo::isshortpermit() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.isShortPermit)
  return isshortpermit_;
}
inline void MarginRatioInfo::set_isshortpermit(bool value) {
  set_has_isshortpermit();
  isshortpermit_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.isShortPermit)
}

// optional double shortPoolRemain = 4;
inline bool MarginRatioInfo::has_shortpoolremain() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MarginRatioInfo::set_has_shortpoolremain() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MarginRatioInfo::clear_has_shortpoolremain() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MarginRatioInfo::clear_shortpoolremain() {
  shortpoolremain_ = 0;
  clear_has_shortpoolremain();
}
inline double MarginRatioInfo::shortpoolremain() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.shortPoolRemain)
  return shortpoolremain_;
}
inline void MarginRatioInfo::set_shortpoolremain(double value) {
  set_has_shortpoolremain();
  shortpoolremain_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.shortPoolRemain)
}

// optional double shortFeeRate = 5;
inline bool MarginRatioInfo::has_shortfeerate() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MarginRatioInfo::set_has_shortfeerate() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MarginRatioInfo::clear_has_shortfeerate() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MarginRatioInfo::clear_shortfeerate() {
  shortfeerate_ = 0;
  clear_has_shortfeerate();
}
inline double MarginRatioInfo::shortfeerate() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.shortFeeRate)
  return shortfeerate_;
}
inline void MarginRatioInfo::set_shortfeerate(double value) {
  set_has_shortfeerate();
  shortfeerate_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.shortFeeRate)
}

// optional double alertLongRatio = 6;
inline bool MarginRatioInfo::has_alertlongratio() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MarginRatioInfo::set_has_alertlongratio() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MarginRatioInfo::clear_has_alertlongratio() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MarginRatioInfo::clear_alertlongratio() {
  alertlongratio_ = 0;
  clear_has_alertlongratio();
}
inline double MarginRatioInfo::alertlongratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.alertLongRatio)
  return alertlongratio_;
}
inline void MarginRatioInfo::set_alertlongratio(double value) {
  set_has_alertlongratio();
  alertlongratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.alertLongRatio)
}

// optional double alertShortRatio = 7;
inline bool MarginRatioInfo::has_alertshortratio() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MarginRatioInfo::set_has_alertshortratio() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MarginRatioInfo::clear_has_alertshortratio() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MarginRatioInfo::clear_alertshortratio() {
  alertshortratio_ = 0;
  clear_has_alertshortratio();
}
inline double MarginRatioInfo::alertshortratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.alertShortRatio)
  return alertshortratio_;
}
inline void MarginRatioInfo::set_alertshortratio(double value) {
  set_has_alertshortratio();
  alertshortratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.alertShortRatio)
}

// optional double imLongRatio = 8;
inline bool MarginRatioInfo::has_imlongratio() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MarginRatioInfo::set_has_imlongratio() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MarginRatioInfo::clear_has_imlongratio() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MarginRatioInfo::clear_imlongratio() {
  imlongratio_ = 0;
  clear_has_imlongratio();
}
inline double MarginRatioInfo::imlongratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.imLongRatio)
  return imlongratio_;
}
inline void MarginRatioInfo::set_imlongratio(double value) {
  set_has_imlongratio();
  imlongratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.imLongRatio)
}

// optional double imShortRatio = 9;
inline bool MarginRatioInfo::has_imshortratio() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MarginRatioInfo::set_has_imshortratio() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MarginRatioInfo::clear_has_imshortratio() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MarginRatioInfo::clear_imshortratio() {
  imshortratio_ = 0;
  clear_has_imshortratio();
}
inline double MarginRatioInfo::imshortratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.imShortRatio)
  return imshortratio_;
}
inline void MarginRatioInfo::set_imshortratio(double value) {
  set_has_imshortratio();
  imshortratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.imShortRatio)
}

// optional double mcmLongRatio = 10;
inline bool MarginRatioInfo::has_mcmlongratio() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MarginRatioInfo::set_has_mcmlongratio() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MarginRatioInfo::clear_has_mcmlongratio() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MarginRatioInfo::clear_mcmlongratio() {
  mcmlongratio_ = 0;
  clear_has_mcmlongratio();
}
inline double MarginRatioInfo::mcmlongratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.mcmLongRatio)
  return mcmlongratio_;
}
inline void MarginRatioInfo::set_mcmlongratio(double value) {
  set_has_mcmlongratio();
  mcmlongratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.mcmLongRatio)
}

// optional double mcmShortRatio = 11;
inline bool MarginRatioInfo::has_mcmshortratio() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void MarginRatioInfo::set_has_mcmshortratio() {
  _has_bits_[0] |= 0x00000100u;
}
inline void MarginRatioInfo::clear_has_mcmshortratio() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void MarginRatioInfo::clear_mcmshortratio() {
  mcmshortratio_ = 0;
  clear_has_mcmshortratio();
}
inline double MarginRatioInfo::mcmshortratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.mcmShortRatio)
  return mcmshortratio_;
}
inline void MarginRatioInfo::set_mcmshortratio(double value) {
  set_has_mcmshortratio();
  mcmshortratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.mcmShortRatio)
}

// optional double mmLongRatio = 12;
inline bool MarginRatioInfo::has_mmlongratio() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MarginRatioInfo::set_has_mmlongratio() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MarginRatioInfo::clear_has_mmlongratio() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MarginRatioInfo::clear_mmlongratio() {
  mmlongratio_ = 0;
  clear_has_mmlongratio();
}
inline double MarginRatioInfo::mmlongratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.mmLongRatio)
  return mmlongratio_;
}
inline void MarginRatioInfo::set_mmlongratio(double value) {
  set_has_mmlongratio();
  mmlongratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.mmLongRatio)
}

// optional double mmShortRatio = 13;
inline bool MarginRatioInfo::has_mmshortratio() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void MarginRatioInfo::set_has_mmshortratio() {
  _has_bits_[0] |= 0x00000400u;
}
inline void MarginRatioInfo::clear_has_mmshortratio() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void MarginRatioInfo::clear_mmshortratio() {
  mmshortratio_ = 0;
  clear_has_mmshortratio();
}
inline double MarginRatioInfo::mmshortratio() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.MarginRatioInfo.mmShortRatio)
  return mmshortratio_;
}
inline void MarginRatioInfo::set_mmshortratio(double value) {
  set_has_mmshortratio();
  mmshortratio_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.MarginRatioInfo.mmShortRatio)
}

// -------------------------------------------------------------------

// C2S

// required .Trd_Common.TrdHeader header = 1;
inline bool C2S::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Trd_Common::TrdHeader& C2S::header() const {
  const ::Trd_Common::TrdHeader* p = header_;
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.C2S.header)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_Common::TrdHeader*>(
      &::Trd_Common::_TrdHeader_default_instance_);
}
inline ::Trd_Common::TrdHeader* C2S::release_header() {
  // @@protoc_insertion_point(field_release:Trd_GetMarginRatio.C2S.header)
  clear_has_header();
  ::Trd_Common::TrdHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::Trd_Common::TrdHeader* C2S::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::Trd_Common::TrdHeader;
  }
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.C2S.header)
  return header_;
}
inline void C2S::set_allocated_header(::Trd_Common::TrdHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:Trd_GetMarginRatio.C2S.header)
}

// repeated .Qot_Common.Security securityList = 2;
inline int C2S::securitylist_size() const {
  return securitylist_.size();
}
inline const ::Qot_Common::Security& C2S::securitylist(int index) const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.C2S.securityList)
  return securitylist_.Get(index);
}
inline ::Qot_Common::Security* C2S::mutable_securitylist(int index) {
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.C2S.securityList)
  return securitylist_.Mutable(index);
}
inline ::Qot_Common::Security* C2S::add_securitylist() {
  // @@protoc_insertion_point(field_add:Trd_GetMarginRatio.C2S.securityList)
  return securitylist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Qot_Common::Security >*
C2S::mutable_securitylist() {
  // @@protoc_insertion_point(field_mutable_list:Trd_GetMarginRatio.C2S.securityList)
  return &securitylist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Qot_Common::Security >&
C2S::securitylist() const {
  // @@protoc_insertion_point(field_list:Trd_GetMarginRatio.C2S.securityList)
  return securitylist_;
}

// -------------------------------------------------------------------

// S2C

// required .Trd_Common.TrdHeader header = 1;
inline bool S2C::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2C::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2C::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Trd_Common::TrdHeader& S2C::header() const {
  const ::Trd_Common::TrdHeader* p = header_;
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.S2C.header)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_Common::TrdHeader*>(
      &::Trd_Common::_TrdHeader_default_instance_);
}
inline ::Trd_Common::TrdHeader* S2C::release_header() {
  // @@protoc_insertion_point(field_release:Trd_GetMarginRatio.S2C.header)
  clear_has_header();
  ::Trd_Common::TrdHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::Trd_Common::TrdHeader* S2C::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::Trd_Common::TrdHeader;
  }
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.S2C.header)
  return header_;
}
inline void S2C::set_allocated_header(::Trd_Common::TrdHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:Trd_GetMarginRatio.S2C.header)
}

// repeated .Trd_GetMarginRatio.MarginRatioInfo marginRatioInfoList = 2;
inline int S2C::marginratioinfolist_size() const {
  return marginratioinfolist_.size();
}
inline void S2C::clear_marginratioinfolist() {
  marginratioinfolist_.Clear();
}
inline const ::Trd_GetMarginRatio::MarginRatioInfo& S2C::marginratioinfolist(int index) const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.S2C.marginRatioInfoList)
  return marginratioinfolist_.Get(index);
}
inline ::Trd_GetMarginRatio::MarginRatioInfo* S2C::mutable_marginratioinfolist(int index) {
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.S2C.marginRatioInfoList)
  return marginratioinfolist_.Mutable(index);
}
inline ::Trd_GetMarginRatio::MarginRatioInfo* S2C::add_marginratioinfolist() {
  // @@protoc_insertion_point(field_add:Trd_GetMarginRatio.S2C.marginRatioInfoList)
  return marginratioinfolist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Trd_GetMarginRatio::MarginRatioInfo >*
S2C::mutable_marginratioinfolist() {
  // @@protoc_insertion_point(field_mutable_list:Trd_GetMarginRatio.S2C.marginRatioInfoList)
  return &marginratioinfolist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Trd_GetMarginRatio::MarginRatioInfo >&
S2C::marginratioinfolist() const {
  // @@protoc_insertion_point(field_list:Trd_GetMarginRatio.S2C.marginRatioInfoList)
  return marginratioinfolist_;
}

// -------------------------------------------------------------------

// Request

// required .Trd_GetMarginRatio.C2S c2s = 1;
inline bool Request::has_c2s() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_c2s() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_c2s() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_c2s() {
  if (c2s_ != NULL) c2s_->Clear();
  clear_has_c2s();
}
inline const ::Trd_GetMarginRatio::C2S& Request::c2s() const {
  const ::Trd_GetMarginRatio::C2S* p = c2s_;
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.Request.c2s)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_GetMarginRatio::C2S*>(
      &::Trd_GetMarginRatio::_C2S_default_instance_);
}
inline ::Trd_GetMarginRatio::C2S* Request::release_c2s() {
  // @@protoc_insertion_point(field_release:Trd_GetMarginRatio.Request.c2s)
  clear_has_c2s();
  ::Trd_GetMarginRatio::C2S* temp = c2s_;
  c2s_ = NULL;
  return temp;
}
inline ::Trd_GetMarginRatio::C2S* Request::mutable_c2s() {
  set_has_c2s();
  if (c2s_ == NULL) {
    c2s_ = new ::Trd_GetMarginRatio::C2S;
  }
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.Request.c2s)
  return c2s_;
}
inline void Request::set_allocated_c2s(::Trd_GetMarginRatio::C2S* c2s) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete c2s_;
  }
  if (c2s) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      c2s = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, c2s, submessage_arena);
    }
    set_has_c2s();
  } else {
    clear_has_c2s();
  }
  c2s_ = c2s;
  // @@protoc_insertion_point(field_set_allocated:Trd_GetMarginRatio.Request.c2s)
}

// -------------------------------------------------------------------

// Response

// required int32 retType = 1 [default = -400];
inline bool Response::has_rettype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_rettype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_rettype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_rettype() {
  rettype_ = -400;
  clear_has_rettype();
}
inline ::google::protobuf::int32 Response::rettype() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.Response.retType)
  return rettype_;
}
inline void Response::set_rettype(::google::protobuf::int32 value) {
  set_has_rettype();
  rettype_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.Response.retType)
}

// optional string retMsg = 2;
inline bool Response::has_retmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_retmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_retmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_retmsg() {
  retmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_retmsg();
}
inline const ::std::string& Response::retmsg() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.Response.retMsg)
  return retmsg_.GetNoArena();
}
inline void Response::set_retmsg(const ::std::string& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.Response.retMsg)
}
#if LANG_CXX11
inline void Response::set_retmsg(::std::string&& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_GetMarginRatio.Response.retMsg)
}
#endif
inline void Response::set_retmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_GetMarginRatio.Response.retMsg)
}
inline void Response::set_retmsg(const char* value, size_t size) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_GetMarginRatio.Response.retMsg)
}
inline ::std::string* Response::mutable_retmsg() {
  set_has_retmsg();
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.Response.retMsg)
  return retmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_retmsg() {
  // @@protoc_insertion_point(field_release:Trd_GetMarginRatio.Response.retMsg)
  clear_has_retmsg();
  return retmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_retmsg(::std::string* retmsg) {
  if (retmsg != NULL) {
    set_has_retmsg();
  } else {
    clear_has_retmsg();
  }
  retmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), retmsg);
  // @@protoc_insertion_point(field_set_allocated:Trd_GetMarginRatio.Response.retMsg)
}

// optional int32 errCode = 3;
inline bool Response::has_errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_errcode() {
  errcode_ = 0;
  clear_has_errcode();
}
inline ::google::protobuf::int32 Response::errcode() const {
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.Response.errCode)
  return errcode_;
}
inline void Response::set_errcode(::google::protobuf::int32 value) {
  set_has_errcode();
  errcode_ = value;
  // @@protoc_insertion_point(field_set:Trd_GetMarginRatio.Response.errCode)
}

// optional .Trd_GetMarginRatio.S2C s2c = 4;
inline bool Response::has_s2c() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_s2c() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_s2c() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_s2c() {
  if (s2c_ != NULL) s2c_->Clear();
  clear_has_s2c();
}
inline const ::Trd_GetMarginRatio::S2C& Response::s2c() const {
  const ::Trd_GetMarginRatio::S2C* p = s2c_;
  // @@protoc_insertion_point(field_get:Trd_GetMarginRatio.Response.s2c)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_GetMarginRatio::S2C*>(
      &::Trd_GetMarginRatio::_S2C_default_instance_);
}
inline ::Trd_GetMarginRatio::S2C* Response::release_s2c() {
  // @@protoc_insertion_point(field_release:Trd_GetMarginRatio.Response.s2c)
  clear_has_s2c();
  ::Trd_GetMarginRatio::S2C* temp = s2c_;
  s2c_ = NULL;
  return temp;
}
inline ::Trd_GetMarginRatio::S2C* Response::mutable_s2c() {
  set_has_s2c();
  if (s2c_ == NULL) {
    s2c_ = new ::Trd_GetMarginRatio::S2C;
  }
  // @@protoc_insertion_point(field_mutable:Trd_GetMarginRatio.Response.s2c)
  return s2c_;
}
inline void Response::set_allocated_s2c(::Trd_GetMarginRatio::S2C* s2c) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete s2c_;
  }
  if (s2c) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      s2c = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, s2c, submessage_arena);
    }
    set_has_s2c();
  } else {
    clear_has_s2c();
  }
  s2c_ = s2c;
  // @@protoc_insertion_point(field_set_allocated:Trd_GetMarginRatio.Response.s2c)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Trd_GetMarginRatio

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Trd_5fGetMarginRatio_2eproto__INCLUDED
